/* ============================================================
A.1 Top 30 Reseller Cities by Sales

Description:
This query identifies the top 30 U.S.-based resellers by total revenue
and aggregates their sales at the city level.

A single address per store is selected to avoid duplication caused by
multiple store addresses. The top 30 resellers are determined based on
total sales (SubTotal), and results are aggregated at the city level.

The final output ranks cities based on the total sales generated by
these top resellers.
============================================================ */

WITH StoreAddress AS (
    -- Select one address per store to avoid duplicates
    SELECT
        s.BusinessEntityID,
        a.City,
        sp.Name AS State,
        ROW_NUMBER() OVER (
            PARTITION BY s.BusinessEntityID
            ORDER BY a.AddressID
        ) AS rn
    FROM Sales.Store s
    JOIN Person.BusinessEntityAddress bea
        ON s.BusinessEntityID = bea.BusinessEntityID
    JOIN Person.Address a
        ON bea.AddressID = a.AddressID
    JOIN Person.StateProvince sp
        ON a.StateProvinceID = sp.StateProvinceID
    JOIN Person.CountryRegion cr
        ON sp.CountryRegionCode = cr.CountryRegionCode
    WHERE cr.Name = 'United States'
),

Top30Stores AS (
    -- Identify top 30 resellers by total sales
    SELECT TOP 30
        s.BusinessEntityID,
        sa.City,
        sa.State,
        SUM(soh.SubTotal) AS StoreSales
    FROM Sales.SalesOrderHeader soh
    JOIN Sales.Customer c
        ON soh.CustomerID = c.CustomerID
    JOIN Sales.Store s
        ON c.StoreID = s.BusinessEntityID
    JOIN StoreAddress sa
        ON s.BusinessEntityID = sa.BusinessEntityID
        AND sa.rn = 1
    WHERE c.StoreID IS NOT NULL
    GROUP BY
        s.BusinessEntityID,
        sa.City,
        sa.State
    ORDER BY SUM(soh.SubTotal) DESC
)

SELECT
    City,
    State,
    SUM(StoreSales) AS TotalCitySales
FROM Top30Stores
GROUP BY
    City,
    State
ORDER BY
    TotalCitySales DESC;



/* ============================================================
A.2 Ranking of US States by Online and Reseller Sales

Description:
This query ranks U.S. states based on online direct-to-consumer sales
and reseller (physical store) sales.

Online sales are identified using OnlineOrderFlag = 1 and PersonType = 'IN'.
Reseller sales are derived from store-based transactions.

The ranking helps identify high-demand states with lower reseller competition.
============================================================ */

WITH OnlineSales AS (
    -- Online direct-to-consumer sales by state
    SELECT
        sp.Name AS State,
        SUM(soh.SubTotal) AS OnlineSales
    FROM Sales.SalesOrderHeader soh
    JOIN Sales.Customer c
        ON soh.CustomerID = c.CustomerID
    JOIN Person.Person p
        ON c.PersonID = p.BusinessEntityID
    JOIN Person.Address a
        ON soh.ShipToAddressID = a.AddressID
    JOIN Person.StateProvince sp
        ON a.StateProvinceID = sp.StateProvinceID
    JOIN Person.CountryRegion cr
        ON sp.CountryRegionCode = cr.CountryRegionCode
    WHERE cr.Name = 'United States'
        AND soh.OnlineOrderFlag = 1
        AND p.PersonType = 'IN'
    GROUP BY
        sp.Name
),

ResellerSales AS (
    -- Reseller (physical store) sales by state
    SELECT
        sp.Name AS State,
        SUM(soh.SubTotal) AS ResellerSales
    FROM Sales.SalesOrderHeader soh
    JOIN Sales.Customer c
        ON soh.CustomerID = c.CustomerID
    JOIN Sales.Store s
        ON c.StoreID = s.BusinessEntityID
    JOIN Person.Address a
        ON soh.ShipToAddressID = a.AddressID
    JOIN Person.StateProvince sp
        ON a.StateProvinceID = sp.StateProvinceID
    JOIN Person.CountryRegion cr
        ON sp.CountryRegionCode = cr.CountryRegionCode
    WHERE cr.Name = 'United States'
        AND c.StoreID IS NOT NULL
    GROUP BY
        sp.Name
)

SELECT
    o.State,
    o.OnlineSales,
    ISNULL(r.ResellerSales, 0) AS ResellerSales,

    -- Ranking by online sales
    RANK() OVER (ORDER BY o.OnlineSales DESC) AS OnlineRank,

    -- Ranking by reseller sales
    RANK() OVER (ORDER BY ISNULL(r.ResellerSales, 0) DESC) AS ResellerRank
FROM OnlineSales o
LEFT JOIN ResellerSales r
    ON o.State = r.State
ORDER BY
    o.OnlineSales DESC;



/* ============================================================
A.3 Market Gap Analysis – Oregon

Description:
This query evaluates market opportunity at the city level in Oregon
by comparing online demand with reseller sales.

Online sales are defined using OnlineOrderFlag = 1 and PersonType = 'IN'.
Reseller sales are derived from store transactions.

The market gap (OnlineSales − ResellerSales) highlights cities with
high unmet demand and low competition.
============================================================ */

WITH Online AS (
    SELECT
        a.City,
        sp.Name AS State,
        SUM(soh.SubTotal) AS OnlineSales
    FROM Sales.SalesOrderHeader soh
    JOIN Sales.Customer c
        ON soh.CustomerID = c.CustomerID
    JOIN Person.Person p
        ON c.PersonID = p.BusinessEntityID
    JOIN Person.Address a
        ON soh.ShipToAddressID = a.AddressID
    JOIN Person.StateProvince sp
        ON a.StateProvinceID = sp.StateProvinceID
    JOIN Person.CountryRegion cr
        ON sp.CountryRegionCode = cr.CountryRegionCode
    WHERE cr.Name = 'United States'
        AND sp.Name = 'Oregon'
        AND soh.OnlineOrderFlag = 1
        AND p.PersonType = 'IN'
    GROUP BY
        a.City,
        sp.Name
),

Resellers AS (
    -- Reseller sales by city
    SELECT
        a.City,
        sp.Name AS State,
        SUM(soh.SubTotal) AS ResellerSales
    FROM Sales.SalesOrderHeader soh
    JOIN Sales.Customer c
        ON soh.CustomerID = c.CustomerID
    JOIN Sales.Store s
        ON c.StoreID = s.BusinessEntityID
    JOIN Person.Address a
        ON soh.ShipToAddressID = a.AddressID
    JOIN Person.StateProvince sp
        ON a.StateProvinceID = sp.StateProvinceID
    JOIN Person.CountryRegion cr
        ON sp.CountryRegionCode = cr.CountryRegionCode
    WHERE cr.Name = 'United States'
        AND sp.Name = 'Oregon'
        AND c.StoreID IS NOT NULL
    GROUP BY
        a.City,
        sp.Name
)

SELECT
    o.City,
    o.OnlineSales,
    ISNULL(r.ResellerSales, 0) AS ResellerSales,

    -- Market gap calculation
    o.OnlineSales - ISNULL(r.ResellerSales, 0) AS MarketGap
FROM Online o
LEFT JOIN Resellers r
    ON o.City = r.City
    AND o.State = r.State
ORDER BY
    MarketGap DESC;



/* ============================================================
A.4 Online Sales Analysis – Maryland

Description:
This query ranks cities in Maryland based on online direct-to-consumer sales.

Online transactions are identified using OnlineOrderFlag = 1 and
PersonType = 'IN'. The shipping address is used to assign sales to locations.

The output identifies Baltimore as the top city, supporting store placement.
============================================================ */

SELECT
    a.City,
    SUM(soh.SubTotal) AS OnlineSales
FROM Sales.SalesOrderHeader soh
JOIN Sales.Customer c
    ON soh.CustomerID = c.CustomerID
JOIN Person.Person p
    ON c.PersonID = p.BusinessEntityID
JOIN Person.Address a
    ON soh.ShipToAddressID = a.AddressID
JOIN Person.StateProvince sp
    ON a.StateProvinceID = sp.StateProvinceID
JOIN Person.CountryRegion cr
    ON sp.CountryRegionCode = cr.CountryRegionCode
WHERE cr.Name = 'United States'
    AND sp.Name = 'Maryland'
    AND soh.OnlineOrderFlag = 1
    AND p.PersonType = 'IN'
GROUP BY
    a.City
ORDER BY
    OnlineSales DESC;
